# CommonFramework configuration
stage: data_reading
model: AthenaRootReader
input_dir: ctd23/data

input_sets:
    train: ctd23/config/trainset.txt
    valid: ctd23/config/evalset.txt
    test:  ctd23/config/testset.txt

stage_dir: tmp/ctd23/feature_store

max_workers: 16

# Feature Configurations
feature_sets:
    hit_features: [hit_id, x, y, z, r, phi, eta, region, module_id,
                   cluster_x_1, cluster_y_1, cluster_z_1, cluster_x_2, cluster_y_2, cluster_z_2,
                   cluster_r_1, cluster_phi_1, cluster_eta_1, cluster_r_2, cluster_phi_2, cluster_eta_2,
                   norm_x_1, norm_y_1, norm_x_2, norm_y_2,
                   norm_z_1, eta_angle_1, phi_angle_1, eta_angle_2, phi_angle_2, norm_z_2]

    track_features: [particle_id, pt, radius, primary, nhits, pdgId, eta_particle, redundant_split_edges]

region_labels:
    1: {hardware: PIXEL, barrel_endcap: -2}
    2: {hardware: STRIP, barrel_endcap: -2}
    3: {hardware: PIXEL, barrel_endcap: 0}
    4: {hardware: STRIP, barrel_endcap: 0}
    5: {hardware: PIXEL, barrel_endcap: 2}
    6: {hardware: STRIP, barrel_endcap: 2}

fix_index_mismatch: True

log_level: INFO
