stage: edge_classifier
model: InteractionGNN2
input_dir: tmp/ctd23/module_map
stage_dir: tmp/ctd23/gnn
project: reproduce_CTD_2023 # Used in logging
accelerator: gpu
devices: 1
nodes: 1
# Dataset parameters
data_split: [1, 8, 1] # Number of [training, validation, testing] examples
dataset_class: GraphDataset
undirected: False
