# CommonFramework configuration
stage: graph_construction
model: PyModuleMap
input_dir: tmp/ctd23/feature_store
stage_dir: tmp/ctd23/module_map
module_map_path: ctd23/data/MMtriplet_1GeV_3hits_noE__merged__sorted.txt

# Dataset parameters
data_split: [1, 8, 1] # Number of [training, validation, testing] examples
batch_size: 20000 #2000000

max_workers: 1

# Evaluation parameters
target_tracks:
  pt: [1000, .inf]
  nhits: [3, .inf]
  primary: True
  pdgId: [not_in, [11, -11]]
  radius: [0., 260.]
  eta_particle: [-4., 4.]
  redundant_split_edges: False

# Plotting parameters
plots:
  graph_construction_efficiency:
    title: Module Map Edge-wise Efficiency
    pt_units: MeV
